name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # يُشغّل يوميًا
  workflow_dispatch: # لتشغيله يدويًا أيضًا

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate snake.svg
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate the animation
        uses: Platane/snk@v3
        with:
          github_user_name: abobakr-lashin
          outputs: |
            dist/snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
